FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY SimpleApp/*.csproj ./
RUN dotnet restore

COPY SimpleApp/. ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# RUN adduser \
#   --disabled-password \
#   --home /app \
#   --gecos '' -u 1001 appuser \
#   && chown -RX appuser /app 

# USER appuser

WORKDIR /app

COPY --from=build-env /app/out .

RUN pwd && ls -la

EXPOSE 80

HEALTHCHECK --interval=5s --timeout=3s CMD curl -X GET "http://localhost:80/" || exit 1

ENTRYPOINT ["dotnet", "SimpleApp.dll"]